# If you'd like to sponsor development of new features or prioritize specific
# items from the roadmap, please reach out to discuss:
#
# Website: https://rauljimenez.info
#
# See docs/TODO.md for the full roadmap and planned features.

custom:
  - https://rauljimenez.info
